"updates":
- "directory": "/"
  "groups":
    "development-dependencies":
      "applies-to": "version-updates"
      "dependency-type": "development"
    "production-dependencies":
      "applies-to": "version-updates"
      "dependency-type": "production"
  "open-pull-requests-limit": 5
  "package-ecosystem": "bundler"
  "reviewers":
  - "@grayscale-labs/dependabot_bundler"
  "schedule":
    "interval": "daily"
"version": 2
