on:
  pull_request:
    types: [opened]

jobs:
  shortcut-create:
    runs-on: ubuntu-latest
    steps:
      - uses: Grayscale-Labs/create-linked-shortcut-story@v2.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          shortcut-token: ${{ secrets.SHORTCUT_TOKEN }}
          project-name: app.gograyscale.com
          team-name: Engineering
          opened-state-name: PR Open
          merged-state-name: Ready for QA
